# Generated by Django 4.0.5 on 2022-06-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tims_ItemList',
            fields=[
                ('image_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('image_main_name', models.CharField(max_length=255)),
                ('image_sub_name', models.CharField(max_length=255)),
                ('image_jigyo', models.CharField(max_length=255)),
                ('image_product', models.CharField(max_length=255)),
                ('image_year', models.IntegerField()),
                ('image_place', models.CharField(max_length=255)),
                ('image_client', models.CharField(max_length=255)),
                ('image_thumbnail_name', models.CharField(max_length=255)),
                ('image_file_name', models.CharField(max_length=255)),
                ('image_description', models.CharField(max_length=255)),
                ('image_status', models.CharField(max_length=255)),
                ('image_parson', models.CharField(max_length=255)),
                ('image_timestamp', models.CharField(max_length=255)),
                ('image_dpt', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tims_image_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tims_RequestList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('request_code', models.CharField(max_length=255)),
                ('request_time', models.CharField(max_length=255)),
                ('request_dpt', models.CharField(max_length=255)),
                ('request_name', models.CharField(max_length=255)),
                ('request_mail', models.CharField(max_length=255)),
                ('request_image', models.CharField(max_length=255)),
                ('request_description', models.CharField(max_length=255)),
                ('request_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tims_request_list',
                'managed': False,
            },
        ),
    ]
